apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: default
  labels:
    app: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: webapp
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: localhost:5001/webapp:v1.0.0
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8080
              name: webapp
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: default
spec:
  selector:
    app: webapp
  type: ClusterIP
  ports:
    - name: webapp
      protocol: TCP
      port: 8080
      targetPort: 8080
